Create uploadSkin.php
MineSkin/examples pull request #4
Opened 2022-10-11 02:43 UTC by CosmoKotik

Upload skin to the mineskin.org using php

2022-10-12 10:26 UTC, InventivetalentDev requested changes

2022-10-12 10:26 UTC, InventivetalentDev commented on php/uploadSkin.php
> +$data = array('model' => 'steve'          //Model       :   steve / alex
model is deprecated, should only use variant

2022-10-12 17:00 UTC, CosmoKotik commented
I have removed model because it is deprecated.

2022-10-13 10:20 UTC, InventivetalentDev approved these changes

2022-10-13 10:21 UTC, merged